version: "3"

services:
  graph:
    image: demo-graph/graph:latest
    environment:
      - PORT=3000
      - MONGO_HOSTNAME=mongodb
      - MONGO_PORT=27017
      - MONGO_USERNAME=demouser
      - MONGO_PASSWORD=demopass
      - MONGO_DATABASENAME=graphdemo
    expose:
      - "3000"
    ports:
      - "8000:3000"
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    command: [--bind_ip_all]
    command: [--auth]
    container_name: mongodb
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - mongodb-volume:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpass
      - MONGO_INITDB_DATABASE=graphdemo
    expose:
      - "27017"
    ports:
      - 27018:27017
volumes:
  mongodb-volume: